---
name: TasmoAdmin
version: dev
slug: sonweb
description: Centrally manage all your Sonoff-Tasmota devices
url: https://github.com/hassio-addons/addon-tasmoadmin
codenotary: codenotary@frenck.dev
webui: "[PROTO:ssl]://[HOST]:[PORT:9541]"
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
ports:
  9541/tcp: 9541
ports_description:
  9541/tcp: TasmoAdmin web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
